context('E2E tests', () => {
    it('display pokemons', () => {
        cy.visit('/')
        cy.wait(1000)
        cy.scrollTo('bottom')
        cy.wait(500)
        cy.get('[data-testid="pokemonId"]').last().click()
        cy.wait(1500)
        cy.get('[data-testid="closeModal"]').click()
        cy.wait(1000)
        cy.scrollTo('bottom')
        cy.scrollTo('bottom')
        cy.wait(1000)
        cy.get('[data-testid="pokemonId"]').last().click()
        cy.wait(1500)
        cy.get('[data-testid="closeModal"]').click()
        cy.scrollTo('top')
    })
})